/*Descrizione:
Visualizzare in pagina 5 numeri casuali  diversi tra loro. Da lì parte un timer di 30 secondi.
Dopo 30 secondi l'utente deve inserire, uno alla volta, i numeri che ha visto precedentemente, tramite i prompt().
Dopo che sono stati inseriti i 5 numeri, il software dice quanti e quali dei numeri da indovinare sono stati individuati.
Consigli del giorno:
* Pensate prima in italiano.
* Dividete in piccoli problemi la consegna.
* Individuate gli elementi di cui avete bisogno per realizzare il programma.
ATTENZIONE:
prompt() e alert() vengono sempre eseguiti prima del resto del codice nel loro scope, quindi dovete trovare un escamotage per "tenerli a bada" finchè le altre operazioni siano state svolte. Siete autorizzate a "imbrogliare" un po' e chiedere all'utente i numeri un pochettino dopo :faccia_leggermente_sorridente: l'importante è far sparire i numeri allo scadere dei 30 secondi!*/



// PRENDO gli elementi  ELEMENTO HTML

const timerDisplay = document.getElementById('timer');
const numberContainer = document.getElementById('number-container')



// CREO L'ARRAY CON I NUMERI RANDOM

/**
 * @param {number} totalNumbers max value of numbers  generated by the function
 * @returns {number[]} array with 5 random numbers
 */

function createNumbers(totalNumbers) {
    const numbers = [];
    while (numbers.length < totalNumbers) {
        let randomNumber;
        do {
            randomNumber = Math.floor((Math.random() * 98) + 1);
        } while (numbers.includes(randomNumber));

        numbers.push(randomNumber);

    }
    return numbers;
}

// INSERISCO I NUMERI RANDOM ALL' INTERNO DELL HTML


const numbers = createNumbers(5);

for (let i = 0; i < numbers.length; i++) {
    let myH3 = `<h3> ${numbers[i]}</h3>`
    numberContainer.innerHTML += myH3;

}



console.log(numbers);

// FUNZIONE countdown

let seconds = 30;
timerDisplay.innerText = seconds;

const countdown = setInterval(function () {
    timerDisplay.innerText = --seconds;
    if (seconds === 0) {
        clearInterval(countdown);
        timerDisplay.innerText = ''

        // AL TERMINE DEL COUNTDOWN FACCIAMO SPARIRE I NUMERI

        numberContainer.style.display = "none"
    }

}, 1000)


// FUNZIONE COUNTDOWN PROMPT e GESTIONE RISULTATO

// CREIAMO UNA VARIABILE PER IL PUNTEGGIO
let userPoints = 0

// SETTIAMO UN COUNTDOWN PER LA COMPARSA DEI PROMPT 

const promptCountdown = setTimeout(function () {

    // CREIAMO UN ARRAY CON I NUMERI INSERITI DALL'UTENTE

    let userNumbers = []

    // CREIAMO UNA VARIABILE PER GESTIRE IL MESSAGGIO DI FINE GIOCO 

    let message = ``


    for (let i = 0; i < numbers.length; i++) {
        userNumber = parseInt(prompt(`inserisci un numero`,))
        userNumbers.push(userNumber)

        // VERIFICHIAMO SE I PROMPT SONO CORRETTI O MENO E SCRIVIAMO UN MESSAGGIO IN BASE A QUESTO

        if (numbers.includes(userNumbers[i])) {
            userPoints++
            message += `${userNumbers[i]} è giusto, `
        } else {
            message += `${userNumbers[i]} è sbagliato, `
        }
    }

    // FACCIAMO APPARIRE I RISULTATI ALL' UTENTE 

    alert(`${message} e il tuo punteggio è di ${userPoints}/${numbers.length}`)
    console.log(userPoints)
    console.log(`${message} e il tuo punteggio è di ${userPoints}/${numbers.length}`)

}, 30500);



