/*Descrizione:
Visualizzare in pagina 5 numeri casuali  diversi tra loro. Da lì parte un timer di 30 secondi.
Dopo 30 secondi l'utente deve inserire, uno alla volta, i numeri che ha visto precedentemente, tramite i prompt().
Dopo che sono stati inseriti i 5 numeri, il software dice quanti e quali dei numeri da indovinare sono stati individuati.
Consigli del giorno:
* Pensate prima in italiano.
* Dividete in piccoli problemi la consegna.
* Individuate gli elementi di cui avete bisogno per realizzare il programma.
ATTENZIONE:
prompt() e alert() vengono sempre eseguiti prima del resto del codice nel loro scope, quindi dovete trovare un escamotage per "tenerli a bada" finchè le altre operazioni siano state svolte. Siete autorizzate a "imbrogliare" un po' e chiedere all'utente i numeri un pochettino dopo :faccia_leggermente_sorridente: l'importante è far sparire i numeri allo scadere dei 30 secondi!*/



// PRENDO gli elementi  ELEMENTO HTML

const timerDisplay = document.getElementById('timer');
const numberContainer = document.getElementById('number-container')


// FUNZIONE TIMER

let seconds = 20;
timerDisplay.innerText = seconds;

const countdown = setInterval(function () {
    timerDisplay.innerText = --seconds;
    if (seconds === 0) {
        clearInterval(countdown);
        timerDisplay.innerText = ''
    }

}, 1000)



// CREO L'ARRAY CON I NUMERI RANDOM

/**
 * @param {number} totalNumbers max value of numbers  generated by the function
 * @returns {number[]} array with 5 random numbers
 */

function createNumbers(totalNumbers) {
    const numbers = [];
    while (numbers.length < totalNumbers) {
        let randomNumber;
        do {
            randomNumber = Math.floor((Math.random() * 98) + 1);
        } while (numbers.includes(randomNumber));

        numbers.push(randomNumber);

    }
    return numbers;
}

// INSERISCO I NUMERI RANDOM ALL' INTERNO DELL HTML

const numbers = createNumbers(5);
console.log(numbers);

